# Generated by Django 4.0.4 on 2022-05-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='taskiq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, verbose_name='question')),
                ('corAnsver', models.CharField(max_length=5, verbose_name='corAnsver')),
                ('answer1', models.CharField(max_length=100, verbose_name='answer1')),
                ('answer2', models.CharField(max_length=100, verbose_name='answer2')),
                ('answer3', models.CharField(max_length=100, verbose_name='answer3')),
                ('answer4', models.CharField(max_length=100, verbose_name='answer4')),
                ('answer5', models.CharField(max_length=100, verbose_name='answer5')),
                ('answer6', models.CharField(max_length=100, verbose_name='answer6')),
            ],
        ),
    ]
